// Purpose: Single source of truth for compiled MQTT entity ids and metadata.
// Invariants: No include guard on purpose; includers redefine MQTT_ENTITY_ROW and include this file multiple times.
#ifdef DEBUG_FREEMEM
MQTT_ENTITY_ROW(entityFreemem, "A2M_freemem", freqOneMin, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
#endif
#ifdef DEBUG_CALLBACKS
MQTT_ENTITY_ROW(entityCallbacks, "A2M_Callbacks", freqTenSec, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
#endif
#ifdef A2M_DEBUG_WIFI
MQTT_ENTITY_ROW(entityRSSI, "A2M_RSSI", freqOneMin, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityBSSID, "A2M_BSSID", freqOneMin, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityTxPower, "A2M_TX_Power", freqOneMin, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityWifiRecon, "A2M_reconnects", freqOneMin, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
#endif
MQTT_ENTITY_ROW(entityRs485Avail, "RS485_Connected", freqNever, false, true, haClassBinaryProblem, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityA2MUptime, "A2M_uptime", freqTenSec, false, false, haClassDuration, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityA2MVersion, "A2M_version", freqOneDay, false, true, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Identity, 0, false)
MQTT_ENTITY_ROW(entityInverterSn, "Inverter_SN", freqOneDay, false, true, haClassInfo, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Identity, 0, false)
MQTT_ENTITY_ROW(entityInverterVersion, "Inverter_version", freqOneDay, false, true, haClassInfo, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Identity, 0, false)
MQTT_ENTITY_ROW(entityEmsSn, "EMS_SN", freqOneDay, false, true, haClassInfo, MqttEntityFamily::System, MqttEntityScope::Inverter, MqttEntityReadKind::Identity, 0, false)
MQTT_ENTITY_ROW(entityEmsVersion, "EMS_version", freqOneDay, false, true, haClassInfo, MqttEntityFamily::System, MqttEntityScope::Inverter, MqttEntityReadKind::Identity, 0, false)
MQTT_ENTITY_ROW(entityBatSoc, "State_of_Charge", freqOneMin, false, true, haClassBattery, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Derived, REG_BATTERY_HOME_R_SOC, true)
MQTT_ENTITY_ROW(entityBatPwr, "ESS_Power", freqTenSec, false, true, haClassPower, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Derived, REG_BATTERY_HOME_R_BATTERY_POWER, true)
MQTT_ENTITY_ROW(entityBatEnergyCharge, "ESS_Energy_Charge", freqOneMin, false, true, haClassEnergy, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_BATTERY_CHARGE_ENERGY_1, false)
MQTT_ENTITY_ROW(entityBatEnergyDischarge, "ESS_Energy_Discharge", freqOneMin, false, true, haClassEnergy, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_BATTERY_DISCHARGE_ENERGY_1, false)
MQTT_ENTITY_ROW(entityGridAvail, "Grid_Connected", freqNever, false, true, haClassBinaryProblem, MqttEntityFamily::Grid, MqttEntityScope::Inverter, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityGridPwr, "Grid_Power", freqTenSec, false, true, haClassPower, MqttEntityFamily::Grid, MqttEntityScope::Inverter, MqttEntityReadKind::Derived, REG_GRID_METER_R_TOTAL_ACTIVE_POWER_1, true)
MQTT_ENTITY_ROW(entityGridEnergyTo, "Grid_Energy_To", freqOneMin, false, true, haClassEnergy, MqttEntityFamily::Grid, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_GRID_METER_R_TOTAL_ENERGY_FEED_TO_GRID_1, false)
MQTT_ENTITY_ROW(entityGridEnergyFrom, "Grid_Energy_From", freqOneMin, false, true, haClassEnergy, MqttEntityFamily::Grid, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_GRID_METER_R_TOTAL_ENERGY_CONSUMED_FROM_GRID_1, false)
MQTT_ENTITY_ROW(entityPvPwr, "Solar_Power", freqTenSec, false, true, haClassPower, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Derived, REG_INVERTER_HOME_R_PV_TOTAL_POWER_1, true)
MQTT_ENTITY_ROW(entityPvEnergy, "Solar_Energy", freqOneMin, false, true, haClassEnergy, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_SYSTEM_OP_R_SYSTEM_TOTAL_PV_ENERGY_1, false)
MQTT_ENTITY_ROW(entityFrequency, "Frequency", freqOneMin, false, true, haClassFrequency, MqttEntityFamily::System, MqttEntityScope::Inverter, MqttEntityReadKind::Aggregate, 0, false)
MQTT_ENTITY_ROW(entityOpMode, "Op_Mode", freqOneMin, true, true, haClassSelect, MqttEntityFamily::System, MqttEntityScope::Inverter, MqttEntityReadKind::Control, 0, false)
MQTT_ENTITY_ROW(entitySocTarget, "SOC_Target", freqOneMin, true, true, haClassBox, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Control, 0, false)
MQTT_ENTITY_ROW(entityChargePwr, "Charge_Power", freqOneMin, true, true, haClassBox, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Control, 0, false)
MQTT_ENTITY_ROW(entityDischargePwr, "Discharge_Power", freqOneMin, true, true, haClassBox, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Control, 0, false)
MQTT_ENTITY_ROW(entityPushPwr, "Push_Power", freqOneMin, true, true, haClassBox, MqttEntityFamily::System, MqttEntityScope::Inverter, MqttEntityReadKind::Control, 0, false)
MQTT_ENTITY_ROW(entityBatCap, "Battery_Capacity", freqOneDay, false, true, haClassInfo, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_BATTERY_CAPACITY, false)
MQTT_ENTITY_ROW(entityBatTemp, "Battery_Temp", freqFiveMin, false, true, haClassTemp, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_MAX_CELL_TEMPERATURE, false)
MQTT_ENTITY_ROW(entityInverterTemp, "Inverter_Temp", freqFiveMin, false, true, haClassTemp, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_INVERTER_TEMP, false)
MQTT_ENTITY_ROW(entityBatFaults, "Battery_Faults", freqOneMin, false, true, haClassBinaryProblem, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Aggregate, REG_BATTERY_HOME_R_BATTERY_FAULT_1, false)
MQTT_ENTITY_ROW(entityBatWarnings, "Battery_Warnings", freqOneMin, false, true, haClassBinaryProblem, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Aggregate, REG_BATTERY_HOME_R_BATTERY_WARNING_1, false)
MQTT_ENTITY_ROW(entityInverterFaults, "Inverter_Faults", freqOneMin, false, true, haClassBinaryProblem, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Aggregate, REG_INVERTER_HOME_R_INVERTER_FAULT_1_1, false)
MQTT_ENTITY_ROW(entityInverterWarnings, "Inverter_Warnings", freqOneMin, false, true, haClassBinaryProblem, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Aggregate, REG_INVERTER_HOME_R_INVERTER_WARNING_1_1, false)
MQTT_ENTITY_ROW(entitySystemFaults, "System_Faults", freqOneMin, false, true, haClassBinaryProblem, MqttEntityFamily::System, MqttEntityScope::Inverter, MqttEntityReadKind::Aggregate, REG_SYSTEM_OP_R_SYSTEM_FAULT_1, false)
MQTT_ENTITY_ROW(entityInverterMode, "Inverter_Mode", freqTenSec, false, true, haClassInfo, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_WORKING_MODE, true)
MQTT_ENTITY_ROW(entityGridReg, "Grid_Regulation", freqOneDay, false, false, haClassInfo, MqttEntityFamily::System, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_SAFETY_TEST_RW_GRID_REGULATION, false)
MQTT_ENTITY_ROW(entityRegNum, "Register_Number", freqOneMin, true, false, haClassBox, MqttEntityFamily::System, MqttEntityScope::Inverter, MqttEntityReadKind::Manual, 0, false)
MQTT_ENTITY_ROW(entityRegValue, "Register_Value", freqOneMin, false, false, haClassInfo, MqttEntityFamily::System, MqttEntityScope::Inverter, MqttEntityReadKind::Manual, 0, false)

// Direct grid meter entities.
MQTT_ENTITY_ROW(entityGridVoltageA, "Grid_Voltage_A", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Grid, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_GRID_METER_R_VOLTAGE_OF_A_PHASE, false)
MQTT_ENTITY_ROW(entityGridVoltageB, "Grid_Voltage_B", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Grid, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_GRID_METER_R_VOLTAGE_OF_B_PHASE, false)
MQTT_ENTITY_ROW(entityGridVoltageC, "Grid_Voltage_C", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Grid, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_GRID_METER_R_VOLTAGE_OF_C_PHASE, false)
MQTT_ENTITY_ROW(entityGridFrequency, "Grid_Frequency", freqDisabled, false, true, haClassFrequency, MqttEntityFamily::Grid, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_GRID_METER_R_FREQUENCY, false)
MQTT_ENTITY_ROW(entityGridActivePowerA, "Grid_Active_Power_A", freqDisabled, false, true, haClassPower, MqttEntityFamily::Grid, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_GRID_METER_R_ACTIVE_POWER_OF_A_PHASE_1, false)
MQTT_ENTITY_ROW(entityGridActivePowerB, "Grid_Active_Power_B", freqDisabled, false, true, haClassPower, MqttEntityFamily::Grid, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_GRID_METER_R_ACTIVE_POWER_OF_B_PHASE_1, false)
MQTT_ENTITY_ROW(entityGridActivePowerC, "Grid_Active_Power_C", freqDisabled, false, true, haClassPower, MqttEntityFamily::Grid, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_GRID_METER_R_ACTIVE_POWER_OF_C_PHASE_1, false)

// Direct PV meter entities.
MQTT_ENTITY_ROW(entityPvMeterEnergyToGrid, "PV_Meter_Energy_To_Grid", freqDisabled, false, true, haClassEnergy, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_PV_METER_R_TOTAL_ENERGY_FEED_TO_GRID_1, false)
MQTT_ENTITY_ROW(entityPvMeterEnergyFromGrid, "PV_Meter_Energy_From_Grid", freqDisabled, false, true, haClassEnergy, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_PV_METER_R_TOTAL_ENERGY_CONSUMED_FROM_GRID_1, false)
MQTT_ENTITY_ROW(entityPvMeterVoltageA, "PV_Meter_Voltage_A", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_PV_METER_R_VOLTAGE_OF_A_PHASE, false)
MQTT_ENTITY_ROW(entityPvMeterVoltageB, "PV_Meter_Voltage_B", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_PV_METER_R_VOLTAGE_OF_B_PHASE, false)
MQTT_ENTITY_ROW(entityPvMeterVoltageC, "PV_Meter_Voltage_C", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_PV_METER_R_VOLTAGE_OF_C_PHASE, false)
MQTT_ENTITY_ROW(entityPvMeterFrequency, "PV_Meter_Frequency", freqDisabled, false, true, haClassFrequency, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_PV_METER_R_FREQUENCY, false)
MQTT_ENTITY_ROW(entityPvMeterActivePowerA, "PV_Meter_Active_Power_A", freqDisabled, false, true, haClassPower, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_PV_METER_R_ACTIVE_POWER_OF_A_PHASE_1, false)
MQTT_ENTITY_ROW(entityPvMeterActivePowerB, "PV_Meter_Active_Power_B", freqDisabled, false, true, haClassPower, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_PV_METER_R_ACTIVE_POWER_OF_B_PHASE_1, false)
MQTT_ENTITY_ROW(entityPvMeterActivePowerC, "PV_Meter_Active_Power_C", freqDisabled, false, true, haClassPower, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_PV_METER_R_ACTIVE_POWER_OF_C_PHASE_1, false)
MQTT_ENTITY_ROW(entityPvMeterPowerTotal, "PV_Meter_Power_Total", freqDisabled, false, true, haClassPower, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_PV_METER_R_TOTAL_ACTIVE_POWER_1, false)

// Direct battery entities.
MQTT_ENTITY_ROW(entityBatteryVoltage, "Battery_Voltage", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_VOLTAGE, false)
MQTT_ENTITY_ROW(entityBatteryStatus, "Battery_Status", freqDisabled, false, true, haClassInfo, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_STATUS, false)
MQTT_ENTITY_ROW(entityBatteryRelayStatus, "Battery_Relay_Status", freqDisabled, false, true, haClassInfo, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_RELAY_STATUS, false)
MQTT_ENTITY_ROW(entityBatteryMinCellVoltagePackId, "Min_Cell_Voltage_Pack_Id", freqDisabled, false, true, haClassInfo, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_PACK_ID_OF_MIN_CELL_VOLTAGE, false)
MQTT_ENTITY_ROW(entityBatteryMinCellVoltageCellId, "Min_Cell_Voltage_Cell_Id", freqDisabled, false, true, haClassInfo, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_CELL_ID_OF_MIN_CELL_VOLTAGE, false)
MQTT_ENTITY_ROW(entityBatteryMinCellVoltage, "Min_Cell_Voltage", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_MIN_CELL_VOLTAGE, false)
MQTT_ENTITY_ROW(entityBatteryMaxCellVoltagePackId, "Max_Cell_Voltage_Pack_Id", freqDisabled, false, true, haClassInfo, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_PACK_ID_OF_MAX_CELL_VOLTAGE, false)
MQTT_ENTITY_ROW(entityBatteryMaxCellVoltageCellId, "Max_Cell_Voltage_Cell_Id", freqDisabled, false, true, haClassInfo, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_CELL_ID_OF_MAX_CELL_VOLTAGE, false)
MQTT_ENTITY_ROW(entityBatteryMaxCellVoltage, "Max_Cell_Voltage", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_MAX_CELL_VOLTAGE, false)
MQTT_ENTITY_ROW(entityBatteryMinCellTemperaturePackId, "Min_Cell_Temperature_Pack_Id", freqDisabled, false, true, haClassInfo, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_PACK_ID_OF_MIN_CELL_TEMPERATURE, false)
MQTT_ENTITY_ROW(entityBatteryMinCellTemperatureCellId, "Min_Cell_Temperature_Cell_Id", freqDisabled, false, true, haClassInfo, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_CELL_ID_OF_MIN_CELL_TEMPERATURE, false)
MQTT_ENTITY_ROW(entityBatteryMinCellTemperature, "Min_Cell_Temperature", freqDisabled, false, true, haClassTemp, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_MIN_CELL_TEMPERATURE, false)
MQTT_ENTITY_ROW(entityBatteryMaxCellTemperaturePackId, "Max_Cell_Temperature_Pack_Id", freqDisabled, false, true, haClassInfo, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_PACK_ID_OF_MAX_CELL_TEMPERATURE, false)
MQTT_ENTITY_ROW(entityBatteryMaxCellTemperatureCellId, "Max_Cell_Temperature_Cell_Id", freqDisabled, false, true, haClassInfo, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_CELL_ID_OF_MAX_CELL_TEMPERATURE, false)
MQTT_ENTITY_ROW(entityBatteryMaxCellTemperature, "Max_Cell_Temperature", freqDisabled, false, true, haClassTemp, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_MAX_CELL_TEMPERATURE, false)
MQTT_ENTITY_ROW(entityBatteryLmuSoftwareVersion, "Battery_LMU_Software_Version", freqDisabled, false, true, haClassInfo, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_LMU_SOFTWARE_VERSION, false)
MQTT_ENTITY_ROW(entityBatteryNumber, "Battery_Number", freqDisabled, false, true, haClassInfo, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_BATTERY_NUMBER, false)
MQTT_ENTITY_ROW(entityBatteryType, "Battery_Type", freqDisabled, false, true, haClassInfo, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_BATTERY_TYPE, false)
MQTT_ENTITY_ROW(entityBatteryChargeFromGridEnergy, "Battery_Charge_From_Grid_Energy", freqDisabled, false, true, haClassEnergy, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_BATTERY_ENERGY_CHARGE_FROM_GRID_1, false)
MQTT_ENTITY_ROW(entityBatteryChargeCutoffVoltage, "Charge_Cutoff_Voltage", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_CHARGE_CUT_OFF_VOLTAGE, false)
MQTT_ENTITY_ROW(entityBatteryDischargeCutoffVoltage, "Discharge_Cutoff_Voltage", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_DISCHARGE_CUT_OFF_VOLTAGE, false)
MQTT_ENTITY_ROW(entityBatterySocCalibration, "Battery_SOC_Calibration", freqDisabled, false, true, haClassInfo, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_BATTERY_SOC_CALIBRATION, false)

// Direct inverter and backup entities.
MQTT_ENTITY_ROW(entityInverterVoltageL1, "Inverter_Voltage_L1", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_VOLTAGE_L1, false)
MQTT_ENTITY_ROW(entityInverterVoltageL2, "Inverter_Voltage_L2", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_VOLTAGE_L2, false)
MQTT_ENTITY_ROW(entityInverterVoltageL3, "Inverter_Voltage_L3", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_VOLTAGE_L3, false)
MQTT_ENTITY_ROW(entityInverterCurrentL1, "Inverter_Current_L1", freqDisabled, false, true, haClassCurrent, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_CURRENT_L1, false)
MQTT_ENTITY_ROW(entityInverterCurrentL2, "Inverter_Current_L2", freqDisabled, false, true, haClassCurrent, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_CURRENT_L2, false)
MQTT_ENTITY_ROW(entityInverterCurrentL3, "Inverter_Current_L3", freqDisabled, false, true, haClassCurrent, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_CURRENT_L3, false)
MQTT_ENTITY_ROW(entityBackupVoltageL1, "Backup_Voltage_L1", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Backup, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_BACKUP_VOLTAGE_L1, false)
MQTT_ENTITY_ROW(entityBackupVoltageL2, "Backup_Voltage_L2", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Backup, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_BACKUP_VOLTAGE_L2, false)
MQTT_ENTITY_ROW(entityBackupVoltageL3, "Backup_Voltage_L3", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Backup, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_BACKUP_VOLTAGE_L3, false)
MQTT_ENTITY_ROW(entityBackupCurrentL1, "Backup_Current_L1", freqDisabled, false, true, haClassCurrent, MqttEntityFamily::Backup, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_BACKUP_CURRENT_L1, false)
MQTT_ENTITY_ROW(entityBackupCurrentL2, "Backup_Current_L2", freqDisabled, false, true, haClassCurrent, MqttEntityFamily::Backup, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_BACKUP_CURRENT_L2, false)
MQTT_ENTITY_ROW(entityBackupCurrentL3, "Backup_Current_L3", freqDisabled, false, true, haClassCurrent, MqttEntityFamily::Backup, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_BACKUP_CURRENT_L3, false)
MQTT_ENTITY_ROW(entityBackupPowerL1, "Backup_Power_L1", freqDisabled, false, true, haClassPower, MqttEntityFamily::Backup, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_BACKUP_POWER_L1_1, false)
MQTT_ENTITY_ROW(entityBackupPowerL2, "Backup_Power_L2", freqDisabled, false, true, haClassPower, MqttEntityFamily::Backup, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_BACKUP_POWER_L2_1, false)
MQTT_ENTITY_ROW(entityBackupPowerL3, "Backup_Power_L3", freqDisabled, false, true, haClassPower, MqttEntityFamily::Backup, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_BACKUP_POWER_L3_1, false)
MQTT_ENTITY_ROW(entityBackupPowerTotal, "Backup_Power_Total", freqDisabled, false, true, haClassPower, MqttEntityFamily::Backup, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_BACKUP_POWER_TOTAL_1, false)
MQTT_ENTITY_ROW(entityInverterFrequency, "Inverter_Frequency", freqDisabled, false, true, haClassFrequency, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_FREQUENCY, false)
MQTT_ENTITY_ROW(entityPv1Voltage, "PV1_Voltage", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_PV1_VOLTAGE, false)
MQTT_ENTITY_ROW(entityPv1Current, "PV1_Current", freqDisabled, false, true, haClassCurrent, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_PV1_CURRENT, false)
MQTT_ENTITY_ROW(entityPv1Power, "PV1_Power", freqDisabled, false, true, haClassPower, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_PV1_POWER_1, false)
MQTT_ENTITY_ROW(entityPv2Voltage, "PV2_Voltage", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_PV2_VOLTAGE, false)
MQTT_ENTITY_ROW(entityPv2Current, "PV2_Current", freqDisabled, false, true, haClassCurrent, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_PV2_CURRENT, false)
MQTT_ENTITY_ROW(entityPv2Power, "PV2_Power", freqDisabled, false, true, haClassPower, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_PV2_POWER_1, false)
MQTT_ENTITY_ROW(entityPv3Voltage, "PV3_Voltage", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_PV3_VOLTAGE, false)
MQTT_ENTITY_ROW(entityPv3Current, "PV3_Current", freqDisabled, false, true, haClassCurrent, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_PV3_CURRENT, false)
MQTT_ENTITY_ROW(entityPv3Power, "PV3_Power", freqDisabled, false, true, haClassPower, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_PV3_POWER_1, false)
MQTT_ENTITY_ROW(entityPv4Voltage, "PV4_Voltage", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_PV4_VOLTAGE, false)
MQTT_ENTITY_ROW(entityPv4Current, "PV4_Current", freqDisabled, false, true, haClassCurrent, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_PV4_CURRENT, false)
MQTT_ENTITY_ROW(entityPv4Power, "PV4_Power", freqDisabled, false, true, haClassPower, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_PV4_POWER_1, false)
MQTT_ENTITY_ROW(entityPv5Voltage, "PV5_Voltage", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_PV5_VOLTAGE, false)
MQTT_ENTITY_ROW(entityPv5Current, "PV5_Current", freqDisabled, false, true, haClassCurrent, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_PV5_CURRENT, false)
MQTT_ENTITY_ROW(entityPv5Power, "PV5_Power", freqDisabled, false, true, haClassPower, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_PV5_POWER_1, false)
MQTT_ENTITY_ROW(entityPv6Voltage, "PV6_Voltage", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_PV6_VOLTAGE, false)
MQTT_ENTITY_ROW(entityPv6Current, "PV6_Current", freqDisabled, false, true, haClassCurrent, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_PV6_CURRENT, false)
MQTT_ENTITY_ROW(entityPv6Power, "PV6_Power", freqDisabled, false, true, haClassPower, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_PV6_POWER_1, false)
MQTT_ENTITY_ROW(entityInverterTotalPvEnergy, "Inverter_Total_PV_Energy", freqDisabled, false, true, haClassEnergy, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_INVERTER_TOTAL_PV_ENERGY_1, false)
MQTT_ENTITY_ROW(entityInverterBatteryVoltage, "Inverter_Battery_Voltage", freqDisabled, false, true, haClassVoltage, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_INVERTER_BAT_VOLTAGE, false)
MQTT_ENTITY_ROW(entityInverterBatteryCurrent, "Inverter_Battery_Current", freqDisabled, false, true, haClassCurrent, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_INVERTER_BAT_CURRENT, false)
MQTT_ENTITY_ROW(entityInverterBatteryPower, "Inverter_Battery_Power", freqDisabled, false, true, haClassPower, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_INVERTER_BAT_POWER, false)
MQTT_ENTITY_ROW(entityInverterTotalReactivePower, "Inverter_Total_Reactive_Power", freqDisabled, false, true, haClassReactivePower, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_INVERTER_TOTAL_REACT_POWER_1, false)
MQTT_ENTITY_ROW(entityInverterTotalApparentPower, "Inverter_Total_Apparent_Power", freqDisabled, false, true, haClassApparentPower, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_INVERTER_TOTAL_APPARENT_POWER_1, false)
MQTT_ENTITY_ROW(entityInverterInternalFrequency, "Inverter_Internal_Frequency", freqDisabled, false, true, haClassFrequency, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_INVERTER_FREQUENCY, false)
MQTT_ENTITY_ROW(entityInverterBackupFrequency, "Inverter_Backup_Frequency", freqDisabled, false, true, haClassFrequency, MqttEntityFamily::Backup, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_INVERTER_BACKUP_FREQUENCY, false)
MQTT_ENTITY_ROW(entityInverterPowerFactor, "Inverter_Power_Factor", freqDisabled, false, true, haClassPowerFactor, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_INVERTER_POWER_FACTOR, false)
MQTT_ENTITY_ROW(entityInverterPvTotalPower, "Inverter_PV_Total_Power", freqDisabled, false, true, haClassPower, MqttEntityFamily::Pv, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_INVERTER_HOME_R_PV_TOTAL_POWER_1, false)
MQTT_ENTITY_ROW(entityInverterArmSoftwareVersion, "Inverter_ARM_Software_Version", freqDisabled, false, true, haClassInfo, MqttEntityFamily::Inverter, MqttEntityScope::Inverter, MqttEntityReadKind::Identity, REG_INVERTER_INFO_R_ARM_SOFTWARE_VERSION_1, false)

// Legacy-compatible direct readbacks added after the long-lived stable catalog
// so existing compact Bucket_Map indices for prior entities remain unchanged.
MQTT_ENTITY_ROW(entityBatteryCurrent, "Battery_Current", freqDisabled, false, true, haClassCurrent, MqttEntityFamily::Battery, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_BATTERY_HOME_R_CURRENT, false)
MQTT_ENTITY_ROW(entityDispatchStart, "Dispatch_Start", freqDisabled, false, true, haClassInfo, MqttEntityFamily::System, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_DISPATCH_RW_DISPATCH_START, false)
MQTT_ENTITY_ROW(entityDispatchMode, "Dispatch_Mode", freqDisabled, false, true, haClassInfo, MqttEntityFamily::System, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_DISPATCH_RW_DISPATCH_MODE, false)
MQTT_ENTITY_ROW(entityDispatchPower, "Dispatch_Power", freqDisabled, false, true, haClassPower, MqttEntityFamily::System, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_DISPATCH_RW_ACTIVE_POWER_1, false)
MQTT_ENTITY_ROW(entityDispatchSoc, "Dispatch_SOC", freqDisabled, false, true, haClassBattery, MqttEntityFamily::System, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_DISPATCH_RW_DISPATCH_SOC, false)
MQTT_ENTITY_ROW(entityDispatchTime, "Dispatch_Time", freqDisabled, false, true, haClassDuration, MqttEntityFamily::System, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_DISPATCH_RW_DISPATCH_TIME_1, false)
MQTT_ENTITY_ROW(entityMaxFeedinPercent, "Max_Feedin_Percent", freqDisabled, true, true, haClassNumber, MqttEntityFamily::System, MqttEntityScope::Inverter, MqttEntityReadKind::Register, REG_SYSTEM_CONFIG_RW_MAX_FEED_INTO_GRID_PERCENT, false)

// Append controller diagnostics after the stable register catalog so legacy
// compact Bucket_Map indices continue to refer to the long-lived entity set.
MQTT_ENTITY_ROW(entityRs485Errors, "A2M_RS485_Errors", freqOneMin, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBudgetExceeded, "Polling_Budget_Exceeded", freqTenSec, false, false, haClassBinaryProblem, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBudgetOverrunCount, "Polling_Budget_Overrun_Count", freqOneMin, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBudgetUsedMs10s, "Polling_Budget_Used_ms_10s", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBudgetLimitMs10s, "Polling_Budget_Limit_ms_10s", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBacklogCount10s, "Polling_Backlog_Count_10s", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBacklogOldestAgeMs10s, "Polling_Backlog_Oldest_Age_ms_10s", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingLastFullCycleAgeMs10s, "Polling_Last_Full_Cycle_Age_ms_10s", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBudgetUsedMs1m, "Polling_Budget_Used_ms_1m", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBudgetLimitMs1m, "Polling_Budget_Limit_ms_1m", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBacklogCount1m, "Polling_Backlog_Count_1m", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBacklogOldestAgeMs1m, "Polling_Backlog_Oldest_Age_ms_1m", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingLastFullCycleAgeMs1m, "Polling_Last_Full_Cycle_Age_ms_1m", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBudgetUsedMs5m, "Polling_Budget_Used_ms_5m", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBudgetLimitMs5m, "Polling_Budget_Limit_ms_5m", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBacklogCount5m, "Polling_Backlog_Count_5m", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBacklogOldestAgeMs5m, "Polling_Backlog_Oldest_Age_ms_5m", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingLastFullCycleAgeMs5m, "Polling_Last_Full_Cycle_Age_ms_5m", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBudgetUsedMs1h, "Polling_Budget_Used_ms_1h", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBudgetLimitMs1h, "Polling_Budget_Limit_ms_1h", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBacklogCount1h, "Polling_Backlog_Count_1h", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBacklogOldestAgeMs1h, "Polling_Backlog_Oldest_Age_ms_1h", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingLastFullCycleAgeMs1h, "Polling_Last_Full_Cycle_Age_ms_1h", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBudgetUsedMs1d, "Polling_Budget_Used_ms_1d", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBudgetLimitMs1d, "Polling_Budget_Limit_ms_1d", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBacklogCount1d, "Polling_Backlog_Count_1d", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBacklogOldestAgeMs1d, "Polling_Backlog_Oldest_Age_ms_1d", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingLastFullCycleAgeMs1d, "Polling_Last_Full_Cycle_Age_ms_1d", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBudgetUsedMsUser, "Polling_Budget_Used_ms_user", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBudgetLimitMsUser, "Polling_Budget_Limit_ms_user", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBacklogCountUser, "Polling_Backlog_Count_user", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingBacklogOldestAgeMsUser, "Polling_Backlog_Oldest_Age_ms_user", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityPollingLastFullCycleAgeMsUser, "Polling_Last_Full_Cycle_Age_ms_user", freqDisabled, false, false, haClassInfo, MqttEntityFamily::Controller, MqttEntityScope::Controller, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityDispatchDuration, "Dispatch_Duration", freqOneMin, true, true, haClassNumber, MqttEntityFamily::System, MqttEntityScope::Inverter, MqttEntityReadKind::Control, 0, false)
MQTT_ENTITY_ROW(entityDispatchRemaining, "Dispatch_Remaining", freqDisabled, false, true, haClassDuration, MqttEntityFamily::System, MqttEntityScope::Inverter, MqttEntityReadKind::Derived, 0, false)
MQTT_ENTITY_ROW(entityDispatchRequestStatus, "Dispatch_Request_Status", freqOneMin, false, false, haClassInfo, MqttEntityFamily::System, MqttEntityScope::Inverter, MqttEntityReadKind::Derived, 0, false)

// Append new inverter-side derived metrics after the long-lived catalog so
// compact legacy Bucket_Map indices continue to resolve to prior entities.
MQTT_ENTITY_ROW(entityLoadPwr, "Load_Power", freqDisabled, false, true, haClassPower, MqttEntityFamily::System, MqttEntityScope::Inverter, MqttEntityReadKind::Derived, REG_CUSTOM_LOAD, true)
